import type { Metadata } from "next";
import "./globals.css";
import { useTranslations } from "next-intl";
import PerfectNavMenu from "@/components/perfect/perfect-nav-menu";
import PerfectBurgerMenu from "@/components/perfect/perfect-burger-menu";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "JSK Bio-fuel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const t = useTranslations();

  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <section>
          <header className="border-b shadow-sm">
            <nav className="flex items-center max-content-width px-4 py-2">
              <h1 className="mr-auto">{t("header.title")}</h1>
              <div className="max-sm:hidden">
                <PerfectNavMenu />
              </div>
              <div className="sm:hidden h-6 ">
                <PerfectBurgerMenu />
              </div>
            </nav>
          </header>
        </section>
        <section>
          <main className="max-content-width">{children}</main>
        </section>
        <section className="mt-auto">
          <footer className="max-content-width">
            <div>Footer</div>
          </footer>
        </section>
      </body>
    </html>
  );
}
